### ISSUE TITLE
Разобраться с XLS

### ISSUE THREAD

**Issue by gagask** [moevm/MSE-2023-moevm-doku_wiki-10#23]
Найти библиотеку для парсинга XLS. Если не получится парсить XLS, указать причины.

**Comment by lixonik** [comment]
**Причина невозможности** парсинга XLS со стилями в формат DokuWiki на стороне клиента заключается в отсутствии подходящих библиотек, которые могут корректно обрабатывать двоичный формат XLS и извлекать стили из него в браузере. Большинство существующих JavaScript-библиотек, таких как SheetJS, обрабатывают формат XLSX, который является современным и более структурированным форматом, основанным на XML. Эти библиотеки не поддерживают сохранение стилей при работе с XLS-файлами.
