### ISSUE TITLE
Create a dokuwiki plugin page

### ISSUE THREAD

**Issue by gagask** [moevm/MSE-2023-moevm-doku_wiki-10#33]
Create a wiki page `plugin:xlsx2dw` and design it according to the [template](https://www.dokuwiki.org/devel:plugin_homepages). More info [here](https://www.dokuwiki.org/devel:plugins#publishing_a_plugin_on_dokuwikiorg).

**Comment by ZhenjaMax** [comment]
https://www.dokuwiki.org/plugin:xlsx2dw
